feat: added util transformToNullableBoolean
Angular-RU/angular-ru-sdk pull request #1082
Opened 2021-11-08 16:41 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2021-11-08 17:00 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +    it('should returne true', () => {
`return`

2021-11-08 17:02 UTC, splincode requested changes

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +    it('should returne false', () => {
`return`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
`validValues` -> `data`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
`validValues` -> `data`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +    it('should returne true', () => {
`return`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
`validValues` -> `data`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
`validValues` -> `data`

2021-11-08 17:02 UTC, splincode commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +    it('should returne null', () => {
`return`

2021-11-09 09:59 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +    it('should returne true', () => {
fixed that

2021-11-09 10:00 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +    it('should returne false', () => {
fixed that

2021-11-09 10:00 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
good name

2021-11-09 10:00 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
good name

2021-11-09 10:00 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +    it('should returne true', () => {
+

2021-11-09 10:00 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
good

2021-11-09 10:01 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +        const validValues: TransformFnParams[] = [
changed

2021-11-09 10:01 UTC, mansurishmuhametov commented on packages/cdk/integration/tests/jest/class-transformer/transform-to-nullable-boolean.spec.ts
> +    it('should returne null', () => {
fixed

2021-11-09 10:09 UTC, splincode approved these changes

2021-11-09 10:18 UTC, merged