Feat/limit concurrency
Angular-RU/angular-ru-sdk pull request #390
Opened 2021-02-05 11:23 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-02-05 14:17 UTC, splincode commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +    it('Maximum of 3 Observables must be executed in parallel. And immediately start the next one if one of them is completed', () => {
лучше с маленькой буквы писать название в тесте

2021-02-05 14:17 UTC, splincode commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +    it('Should wait until one observable complete before start another if limit is reached', () => {
лучше с маленькой буквы писать название в тесте

2021-02-05 14:17 UTC, splincode commented on packages/http/src/data-http-client.module.ts
> +                LimitConcurrencyService
лучше перед ..clients

2021-02-05 14:32 UTC, splincode commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +    it('Should throw an error if limitConcurrency = -1', () => {
лучше с маленькой буквы писать название в тесте

2021-02-05 14:32 UTC, splincode approved these changes

2021-02-05 14:32 UTC, splincode commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +    it('Should throw an error if limitConcurrency = 0', () => {
лучше с маленькой буквы писать название в тесте

2021-02-05 15:33 UTC, Schirbak commented
косметические поправки, а так lgtm

2021-02-06 08:10 UTC, splincode commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +import { LimitConcurrencyService } from '../../../src/services/limit-concurency.service';
можно ли также написать тест с использование какого-нибудь клиента?

```
class MyClient extends DataHttpClient {}


// ...

TestBed.inject(MyClient);
// написать 3 теста и проверить вызов запросов с лимитами 0, 1, 5
```

2021-02-16 11:25 UTC, mansurishmuhametov commented on packages/http/integration/tests/services/limit-concurrency.service.spec.ts
> +    it('Maximum of 3 Observables must be executed in parallel. And immediately start the next one if one of them is completed', () => {
поправил

2021-02-17 09:47 UTC, splincode commented on packages/http/src/services/data-http.client.ts
> +    constructor(private readonly limitConcurrencyService: LimitConcurrencyService) {
@mansurishmuhametov

2021-02-17 09:47 UTC, splincode commented on packages/http/src/services/limit-concurency.service.ts
> +    public queue<R>(request: Observable<R>, limitConcurrency: number): Observable<R> {
@mansurishmuhametov

2021-02-17 09:50 UTC, splincode requested changes

2021-02-17 09:50 UTC, splincode commented on packages/http/typings/src/interfaces/data-client-request-options.ts
> +    limitConcurrency?: number;
нужно сделать по умолчанию 255 и написать тест с передачей Infinity
также необходимо написать документацию с примером и картинкой из network браузера, где лимит указываешь 5 и отправлял при этом 20 запросов

2021-02-17 09:56 UTC, mansurishmuhametov commented on packages/http/src/services/data-http.client.ts
> +    constructor(private readonly limitConcurrencyService: LimitConcurrencyService) {
поправил

2021-02-17 09:58 UTC, mansurishmuhametov commented on packages/http/src/services/limit-concurency.service.ts
> +    public queue<R>(request: Observable<R>, limitConcurrency: number): Observable<R> {
переименовал

2021-02-18 07:46 UTC, Schirbak commented on packages/http/src/services/limit-concurency.service.ts
> +    private activeRequestCount: number = 0;
по-моему `activeRequestCount === requestQueue.length`

2021-02-18 07:48 UTC, Schirbak commented on packages/http/src/services/limit-concurency.service.ts
> +    private activeRequestCount: number = 0;
а, не, я познал схему

2021-02-18 07:55 UTC, splincode requested changes

2021-02-18 07:55 UTC, splincode commented on packages/http/src/services/limit-concurency.service.ts
> +const DEFAULT_LIMIT: number = 255;
я думал, ты по умолчанию установишь это значение сюда `options.clientOptions.limitConcurrency`

```ts
export const DATA_REQUEST_OPTIONS_CONFIG: DataClientRequestOptions = {
    baseUrl: null,
    hostUrl: null,
    body: null,
    headers: {},
    queryParams: {},
    emitSuccess: false,
    emitFailure: true,
    responseType: 'json',
    reportProgress: true,
    additionalOptions: {},
    nullInsteadEmpty: true,
    limitConcurrency: 255,
};
```

и вытаскивать будешь отсюда:
`options.limitConcurrency`

2021-02-18 07:55 UTC, splincode commented on packages/http/src/services/limit-concurency.service.ts
> +        if (limitConcurrency === Infinity) {
Я как раз и подразумевал, что наоборот) пользователь сможет убрать ограничения, использую `Infinity`, а не запрещать ему. Также в доке можно было бы об этом рассказать

2021-02-18 07:55 UTC, splincode commented on packages/http/typings/src/interfaces/data-client-request-options.ts
> +    limitConcurrency?: number;
Лучше сделать это поле обязательным

2021-02-18 07:55 UTC, splincode commented on packages/http/src/services/data-http.client.ts
> +            options.clientOptions.limitConcurrency
```options.limitConcurrency```

2021-02-19 08:55 UTC, mansurishmuhametov commented on packages/http/src/services/limit-concurency.service.ts
> +const DEFAULT_LIMIT: number = 255;
поправил

2021-02-19 08:59 UTC, splincode commented on packages/http/integration/tests/limit-concurrency/unsubscribe.spec.ts
> +            return this.restTemplate();
сделай им всем в тесте delay(2000)

2021-02-19 09:41 UTC, mansurishmuhametov commented on packages/http/src/services/limit-concurency.service.ts
> +        if (limitConcurrency === Infinity) {
не правильно понял ))
поправил

2021-02-19 09:41 UTC, mansurishmuhametov commented on packages/http/typings/src/interfaces/data-client-request-options.ts
> +    limitConcurrency?: number;
это да !

2021-02-19 09:44 UTC, mansurishmuhametov commented on packages/http/src/services/data-http.client.ts
> +            options.clientOptions.limitConcurrency
правильно все же
options.clientOptions.limitConcurrency

2021-02-19 09:46 UTC, splincode commented on packages/http/src/services/data-http.client.ts
> +            options.clientOptions.limitConcurrency
суть в том, что clientOptions был сделан для того, чтобы ты мог кастомные свойства пробрасывать, это не кастомное свойство, оно должно быть на уровне выше и обязательным

2021-02-19 09:47 UTC, mansurishmuhametov commented on packages/http/integration/tests/limit-concurrency/unsubscribe.spec.ts
> +            return this.restTemplate();
добавил

2021-02-19 09:48 UTC, splincode commented on packages/http/src/services/data-http.client.ts
> +            options.clientOptions.limitConcurrency
а не сорян, я похоже тут реально затупил(((

2021-02-19 10:01 UTC, splincode commented on packages/http/src/services/limit-concurency.service.ts
> +        if (limitConcurrency === Infinity) {
я думаю этот if надо поставить выше, если он сразу Infinity, то и валидировать нечего

2021-02-19 10:36 UTC, splincode commented on packages/http/integration/tests/limit-concurrency/unsubscribe.spec.ts
> +            return this.restTemplate();
пока не вижу в коде)

2021-02-19 10:37 UTC, splincode commented on packages/http/src/services/limit-concurency.service.ts
> +        if (limitConcurrency === Infinity) {
@mansurishmuhametov

2021-02-19 10:46 UTC, mansurishmuhametov commented on packages/http/integration/tests/limit-concurrency/unsubscribe.spec.ts
> +            return this.restTemplate();
собралось

2021-02-19 11:01 UTC, mansurishmuhametov commented on packages/http/src/services/limit-concurency.service.ts
> +        if (limitConcurrency === Infinity) {
поправил

2021-02-19 11:03 UTC, splincode commented on packages/http/integration/tests/limit-concurrency/unsubscribe.spec.ts
> +            return this.restTemplate();
я думал ты им тут delay поставишь)

```ts
 @Get(`${api}7`) public getData_7(): Observable<string> {
            return this.emulate();
        }

        @Get(`${api}8`) public getData_8(): Observable<string> {
            return this.emulate();
        }

       private emulate() {
           return this.restTemplate().pipe(2000);
        }
}
```

2021-02-19 13:28 UTC, splincode approved these changes

2021-02-19 13:29 UTC, merged