feat(@angular-ru/ng-table-builder): add row-css-classes input into TableBuilder
Angular-RU/angular-ru-sdk pull request #420
Opened 2021-02-17 16:16 UTC by Schirbak

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[] Yes
[x] No
```

## Other information

2021-02-17 18:49 UTC, splincode requested changes

2021-02-17 18:49 UTC, splincode commented on packages/ng-table-builder/src/components/table-tbody/table-tbody.component.html
> +            [ngClass]="(columnSchema?.td?.class || []).concat(rowCssClasses[item[primaryKey!]] || [])"
Хорошая фича, единственное, было бы здорово, если можно было бы тут сделать через pipe, чтобы concat вызывался не на каждый cd

2021-02-18 17:04 UTC, Schirbak commented on packages/ng-table-builder/src/components/table-tbody/table-tbody.component.html
> +            [ngClass]="(columnSchema?.td?.class || []).concat(rowCssClasses[item[primaryKey!]] || [])"
всё, пайп запилен

2021-02-18 17:27 UTC, splincode approved these changes

2021-02-18 17:27 UTC, splincode commented
LGTM 🔥

2021-02-18 21:28 UTC, merged