feat(@angular-ru/http): url sergments
Angular-RU/angular-ru-sdk pull request #481
Opened 2021-03-17 13:02 UTC by nikitasadchikov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2021-03-17 13:10 UTC, splincode requested changes

2021-03-17 13:10 UTC, splincode commented on packages/http/decorators/src/host-url.decorator.ts
> +export function HostUrl(hostUrl: string | null = null): (clientClass: ClassType) => void {
`string | null = null` -> `string = ''`

2021-03-17 13:10 UTC, splincode commented on packages/http/decorators/src/rest-client.decorator.ts
> +export function RestClient(restUrl: string = '/'): (clientClass: ClassType) => void {
'/' -> ''

2021-03-17 13:10 UTC, splincode commented on packages/http/src/configs/data-request-options.config.ts
> +    restUrl: null,
не уверен, что это актуально тут (restUrl и pathUrl)
так как эти url относятся к локальным клиентам, а не для всего приложения

2021-03-17 13:10 UTC, splincode commented on packages/http/typings/src/interfaces/data-client-request-options.ts
> +    pathUrl: string | null;
не уверен, что это должно быть тут

2021-03-17 13:10 UTC, splincode commented on packages/http/utils/src/build-url.ts
> +        const clearPath: string = getPathWithoutQueryParams(path || pathUrl);
напомни почему тут `path || pathUrl`

2021-03-17 19:34 UTC, nikitasadchikov commented on packages/http/utils/src/build-url.ts
> +        const clearPath: string = getPathWithoutQueryParams(path || pathUrl);
Это своего рода был mvp, пометил пр даже как драфт) кинул, чтобы вы сразу посмотрели и, возможно, указали на какие-либо концептуальные неточности или спорные моменты
А здесь так, потому что изначально у функции была сигнатура buildUrl(path: string, { hostUrl, baseUrl }: DataUrlPathSegment), но потом в DataUrlPathSegment добавили ещё restUrl и pathUrl; пробовал различные способы передать и работать с pathUrl. В любом случае двух источников у одного и того же быть не должно, это уже поправил. В ближайшем коммите со всеми остальными замечаниями отправлю

2021-03-17 19:43 UTC, splincode commented on packages/http/utils/src/build-url.ts
> +        const clearPath: string = getPathWithoutQueryParams(path || pathUrl);
ты это) не перерабатывай) рабочий день в 19 заканчивается)

2021-03-17 19:55 UTC, nikitasadchikov commented on packages/http/utils/src/build-url.ts
> +        const clearPath: string = getPathWithoutQueryParams(path || pathUrl);
всё, молчу)

2021-03-18 11:08 UTC, splincode requested changes

2021-03-18 11:08 UTC, splincode commented on packages/http/utils/src/make-url-segments.ts
> +    const path: string = pathUrl.trim();
а почему в `?.trim() || ''` эти штуки сразу не делать в replaceLeadingAndTrailingSlashes?)

2021-03-18 11:08 UTC, splincode commented on packages/http/decorators/src/base-url.decorator.ts
>          validateRestClient('@BaseUrl', clientClass);
переименуешь заоодно `validateRestClient` в `validateHttpParentDecorator`

2021-03-18 13:41 UTC, nikitasadchikov commented on packages/http/utils/src/make-url-segments.ts
> +    const path: string = pathUrl.trim();
Думал про это, мне показалось, что получается слишком нагромождённо, если я правильно понял твою идею

2021-03-18 14:25 UTC, splincode commented on packages/http/utils/src/make-url-segments.ts
> +    };
))

```ts
    return {
        hostUrl: replaceLeadingAndTrailingSlashes(hostUrl),
        baseUrl: replaceLeadingAndTrailingSlashes(baseUrl),
        restUrl: replaceLeadingAndTrailingSlashes(restUrl),
        pathUrl: replaceLeadingAndTrailingSlashes(pathUrl)
    };
```

2021-03-18 14:25 UTC, splincode approved these changes

2021-03-18 15:45 UTC, splincode approved these changes

2021-03-18 17:45 UTC, splincode approved these changes

2021-03-18 17:45 UTC, merged