feat: added validator 'isAnyRequiredValidator' and util 'isAny'
Angular-RU/angular-ru-sdk pull request #483
Opened 2021-03-17 15:27 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Added util for validating form group controls. Is any value is present

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-03-17 17:32 UTC, splincode commented on packages/common/validators/src/required-some.validator.ts
> +export function requiredSomeValidator(of?: string[]): ValidatorFn {
```ts
requiredSomeValidator<T>(keys: (keyof T | string[]))
```

2021-03-17 17:39 UTC, splincode requested changes

2021-03-17 17:39 UTC, splincode commented on packages/common/validators/src/required-some.validator.ts
> +        }
Лучше сделать иначе

```ts
const valueList: Any[] = of?.map((control: string): Any => formGroupValue[control]) ?? Object.values(formGroupValue);

if (valueList.some(isNotNil)) {
            return null;
        }
```


```ts
const formGroupValue: T = formGroup.getRawValue();
let result: ValidationErrors | null = { [VALIDATOR_TYPE]: true };

for (const key of keys) {
   const value: Any = getValueByPath(formGroupValue, key);
   if (isNotNil(value)) {
      result = null;
      break;
   }
}

return result;
```

2021-03-17 17:39 UTC, splincode commented on packages/common/validators/src/utils/assert-form-group.ts
> +        throw new Error(`${controlName} must be used on form group`);
@Schirbak и все же я сомневаюсь в корректности названия этого аргумента

2021-03-17 17:39 UTC, splincode commented on packages/common/validators/src/required-some.validator.ts
> +export function requiredSomeValidator(of?: string[]): ValidatorFn {
requiredSomeValidator -> requiredSomeValueByKeysValidator

2021-03-17 17:39 UTC, splincode commented on packages/common/integration/tests/validators/complex-required-validator.spec.ts
> +    it('should be valid if there is empty list as a parameter', () => {
создай тест с уровнем вложенности 3 и передавай ключи в формате

```ts
requiredSomeValidator([ 'a', 'a.b', 'a.b.c' ])
```

2021-03-18 07:19 UTC, Schirbak commented on packages/common/validators/src/utils/assert-form-group.ts
> +        throw new Error(`${controlName} must be used on form group`);
предложи тогда просто чтобы уже не холиварить, как правильно в самом начале убедиться, что нам просунули FormGroup.

2021-03-18 11:09 UTC, splincode approved these changes

2021-03-18 12:45 UTC, Schirbak approved these changes

2021-03-18 12:46 UTC, merged