Feat/convert date
Angular-RU/angular-ru-sdk pull request #502
Opened 2021-03-29 13:25 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Added date converters: shiftDate, startOfDay, endOfDay

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-03-29 13:40 UTC, Schirbak requested changes

2021-03-29 13:40 UTC, Schirbak commented on packages/common/date/src/shift-date/shift-date.ts
> +    const years: number = date.getFullYear() + (interval.years || 0);
не хочу мутабельную :( давай клонировать эту дату

2021-03-29 13:40 UTC, Schirbak commented on packages/common/date/src/shift-date/interval.interface.ts
> +export interface Interval {
давай переименуем в DateShiftDescriptor
@splincode як думаешь?

2021-03-29 13:42 UTC, splincode commented on packages/common/date/src/shift-date/interval.interface.ts
> +export interface Interval {
поддержива

2021-03-29 14:25 UTC, splincode commented on packages/common/integration/tests/date/serial-date.spec.ts
> +xdescribe('[TEST]: Date', (): void => {
xdescribe?

2021-03-30 15:13 UTC, splincode submitted a review, later dismissed

2021-03-30 17:59 UTC, splincode approved these changes

2021-03-31 08:25 UTC, Schirbak approved these changes

2021-03-31 08:26 UTC, merged