feat(@angular-ru/common/utils): add downloadFile utility
Angular-RU/angular-ru-sdk pull request #517
Opened 2021-04-09 09:23 UTC by nikitasadchikov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-04-09 09:29 UTC, Schirbak commented on packages/common/utils/src/download-file.ts
> +    anchor.download = `${file.name}.${file.extension}`;
@nikitasadchikov @splincode не находите это злом? а вдруг ~~нам~~ понадобится скачивать Dockerfile?

2021-04-09 09:29 UTC, Schirbak commented on packages/ng-excel-builder/src/excel-builder.service.ts
> +                const name: string = `${workbook.filename}.${toFormatDateTime()}`;
ставлю класс

2021-04-09 09:54 UTC, splincode requested changes

2021-04-09 09:54 UTC, splincode commented on packages/common/utils/src/download-file.ts
> +    anchor.download = `${file.name}.${file.extension}`;
@Schirbak Yes, you are right, so I suggest doing

```ts
const filePath = [file.name, file.extension].filter(Boolean).join('.');
```

where `name` and `extension` is nullable value

and throw exception when name and extensions is empty

2021-04-09 09:54 UTC, splincode commented on packages/common/utils/src/download-file.ts
> +    name: string;
`name?: string | null;`
`extension?: string | null;`

2021-04-09 09:54 UTC, splincode commented on packages/common/utils/src/download-file.ts
> +interface FileToDownloadInfo {
export

2021-04-09 11:35 UTC, Schirbak commented on packages/common/utils/src/download-file.ts
> +    anchor.download = `${file.name}.${file.extension}`;
Zachem nullable? Zachem voobshe extension otdelno. Mozhno zhe prosto 
```ts
downloadFile(blob, `${myName}.xlsx`)

2021-04-09 11:36 UTC, Schirbak commented on packages/common/utils/src/download-file.ts
> +    anchor.download = `${file.name}.${file.extension}`;
ну так-то конечно типа вкусовщина, лан

2021-04-09 11:36 UTC, Schirbak submitted a review, later dismissed

2021-04-09 12:06 UTC, mansurishmuhametov submitted a review, later dismissed

2021-04-12 15:21 UTC, splincode approved these changes

2021-04-12 15:21 UTC, Schirbak approved these changes

2021-04-12 15:51 UTC, merged

2021-04-12 20:28 UTC, splincode commented on packages/common/utils/src/download-file.ts
> +    anchor.download = `${file.name}.${file.extension}`;
you can use overload for current util))