feat: added common utils
Angular-RU/angular-ru-sdk pull request #542
Opened 2021-04-21 15:04 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-04-21 15:08 UTC, Schirbak requested changes

2021-04-21 15:08 UTC, Schirbak commented on packages/common/utils/src/check-some-value-is-false.ts
> +    if (values.length === 0) {
no need to dis

2021-04-21 15:08 UTC, Schirbak commented on packages/common/utils/src/check-every-value-is-true.ts
> +    if (values.length === 0) {
dis

2021-04-21 15:08 UTC, Schirbak commented on packages/common/utils/src/check-every-value-is-false.ts
> +    if (values.length === 0) {
and dis

2021-04-21 15:08 UTC, Schirbak commented on packages/common/utils/src/check-some-value-is-true.ts
> +    return values.some(isTrue);
like this

2021-04-21 15:42 UTC, mansurishmuhametov commented on packages/common/utils/src/check-some-value-is-false.ts
> +    if (values.length === 0) {
removed
turned out to be superfluous

2021-04-21 16:11 UTC, Schirbak submitted a review, later dismissed

2021-04-21 16:53 UTC, splincode requested changes

2021-04-21 16:53 UTC, splincode commented on packages/common/utils/src/check-every-value-is-true.ts
> +    if (values.length === 0) {
use ternary operator

2021-04-21 16:53 UTC, splincode commented on packages/common/utils/src/check-every-value-is-false.ts
> +    if (values.length === 0) {
use ternary operator

2021-04-22 07:06 UTC, splincode commented on packages/common/utils/src/check-every-value-is-false.ts
> +    if (values.length === 0) {
and this?)

2021-04-22 09:24 UTC, splincode approved these changes

2021-04-22 09:26 UTC, Schirbak approved these changes

2021-04-22 09:31 UTC, merged