feat: added eslint-plugin-i18n-json
Angular-RU/angular-ru-sdk pull request #639
Opened 2021-05-27 10:18 UTC by mansurishmuhametov

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-05-27 10:40 UTC, Schirbak requested changes
most of our eslint rules are covered with tests. i see you added some test files in `integration` folder. but you should pack it more deeper — in the file-suites folder and update tests with new error messages.

2021-05-27 10:40 UTC, Schirbak commented on package.json
> +        "lint:i18n": "yarn eslint --format node_modules/eslint-plugin-i18n-json/formatter.js **/i18n/**/*.json",
did you forgot to remove this line?

2021-05-27 10:40 UTC, Schirbak commented on packages/eslint-config/index.js
> +                'i18n-json/sorted-keys': [
can you put it in one line?

2021-05-27 12:35 UTC, splincode submitted a review, later dismissed

2021-06-11 07:41 UTC, mansurishmuhametov commented on packages/eslint-config/index.js
> +                'i18n-json/sorted-keys': [
sure

2021-06-11 10:26 UTC, splincode approved these changes

2021-06-11 10:44 UTC, Schirbak approved these changes

2021-06-11 10:47 UTC, merged