feat(@angular-ru/ng-excel-builder): add column width feature & refactor
Angular-RU/angular-ru-sdk pull request #700
Opened 2021-06-24 15:02 UTC by Schirbak

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2021-06-24 16:22 UTC, splincode commented
Please, add test

2021-06-24 16:24 UTC, splincode requested changes

2021-06-24 16:24 UTC, splincode commented on packages/common/table-utils/src/interfaces/rules-descriptor.ts
> +    includeKeys?: string[];
need test for that cases

2021-06-27 19:05 UTC, splincode requested changes
Great job!!! I have some recommendation

2021-06-27 19:05 UTC, splincode commented on packages/ng-excel-builder/src/domain/excel-worksheet.ts
> +    columnParameters?: PlainObjectOf<ColumnParameters>;
need improved typings

https://www.typescriptlang.org/play?#code/C4TwDgpgBAUg9gSwHYB4DSAaKAFAfFAXijSggA9gIkATAZyluACdkBzKAHyiQFcBbAEYQmUAPwBYAFBQZOUhSp0GzNp278hIidNkADACQBvNAF8jAInPzKNetjFRLUAFyOAdObOHsJ3VNku3BAAbsKBSCHCANxSsZKgkDhMIYRQANoRoUxYAAxYAIxYAExYAMxYACxYAKxYAGxYAOxYABxYAJwFef6y+YVQ+SUD5QNVA7UDDQPNA20DnVBFeVBuqzlpALobcQnQ2ACGwAAWtCgAKlgAItaK9LyCYUT5OfhEaZcbN7bpmcKfokEsoEzl8lHABAArCAAY2AYh6MkM6RIyCgAGsICA4AAzKBnDYAWlErhI5BsSkYLCQ7C49008J0ARkBmMvjU8GQ6CwB2OpzOaTQG25yWC7w2uFwCKZrl+TClJjSGKxuPxgUsO3A0AAMhB9qE+VdQXcNI8Bi9UmKjT9Ikx-oCwq4QWTblBwVDYQyAkiBVBUUqcXjCcTYIhUJgoDq9RA+QKhUkQmKJVAFf6VZ9XJYYpINYkAHLRyjUADykJhwDOmtShil+1clLYWYCAjrKmpjdkEUYrmrjKZ0JbVNY7ZkJmHruOwnzXagPaZsn7ykHY9HUhX2filanhZL7uAPJOqX3py3EGLpdhFcguCzAHob459lYuOYBE-HJ3gG-zHAJ0wt1+PzcaEvx-I5JwLIDzCkXYoBPM9d0jfVUkQ6MUDgncy0vCBJUkO8oBg9Dz2AFD6DecxH0+Lg0hfcxKPScwP3MLBzGAujqNA8DGCYxxWLiZBKCYbF9mhaAzmSaBZ1kAAbCBsWAR1xIwKUWFYI55LxRSpWoQ5a0XNhVziPCYLEiAIBI5DdX1c5xOvKA8NoOAmCYEAsGhOA+DABAZJEQBeDcAbp3AGxiHzAGo9qQjMrEyzMs6NUnMbTgEfNRzBkuS3HixLnxUtS0p0r8UuANx8pyhKnzC+9ktkgqsoK9Kv2qwrKuKjLHHq+raqSorOsa9quDKxwutStrco6xr6qKnqVlWM1BigPhHOgVY3DUPrzFahBVKq9bsrWja3B27ats23bapzUTxPMogSOs0yymvPrjPO6LSJkOLhufca3paw6mryxqPpK5bcPKoqhoBzLvv+5rVu+0HH1OqAAFkQAAcSoYQEGhLDzitN0y1eGcpSVWhXAAQSc-YQBQI9zglLM1ykNykEYfCC1cJHUYiFhMc1NCC1PDCL01fHJJkInXGox9mMA3jJBMOJyDARy4X44QhJEnApP2ZABbhEX0iVAc2A2Vx9iQEA6biaDKwAYTgKT+CQIswGABA4CZ7GiGwTXtaI4WpUVTFfSQHBDhOc5ilwDZg3rakoAt9dGeZyhGCKVxbftvhHed133aRZt1AebIoGobsoAXapk2TYWoHzgByIpa+Y6hINcWvqlr5MoiAA

![image](https://user-images.githubusercontent.com/12021443/123556357-823afb80-d793-11eb-8c56-2bbc90914c70.png)

Use Paths from `@angular-ru/common/typings`;

2021-06-27 19:43 UTC, Schirbak commented on packages/ng-excel-builder/src/domain/excel-worksheet.ts
> +    columnParameters?: PlainObjectOf<ColumnParameters>;
it little more complexive, leave as proposal

2021-06-27 19:43 UTC, Schirbak commented on packages/ng-excel-builder/src/domain/excel-worksheet.ts
> +    columnParameters?: PlainObjectOf<ColumnParameters>;
<img width="1045" alt="Снимок экрана 2021-06-27 в 22 43 28" src="https://user-images.githubusercontent.com/33288503/123557340-19ef1880-d799-11eb-999e-4ce00182ba7f.png">

2021-06-27 19:44 UTC, Schirbak commented on packages/ng-excel-builder/src/domain/excel-worksheet.ts
> +    columnParameters?: PlainObjectOf<ColumnParameters>;
first we need to deal with values' types

2021-06-27 20:35 UTC, splincode commented on packages/ng-excel-builder/src/domain/excel-worksheet.ts
> +    columnParameters?: PlainObjectOf<ColumnParameters>;
okey

2021-06-28 06:54 UTC, Schirbak commented on packages/ng-excel-builder/integration/tests/helpers/file-utils.ts
> +export function readFromBlob(blob: Blob): Promise<string> {
r e d u n d a n t

2021-06-28 06:56 UTC, splincode commented on packages/ng-excel-builder/integration/tests/helpers/file-utils.ts
> +export function readFromBlob(blob: Blob): Promise<string> {
I very often see utilities that duplicate themselves in different packages, in different tests, but I agree that this can be discussed later

2021-06-28 06:57 UTC, splincode approved these changes

2021-06-28 08:49 UTC, merged